### PR TITLE
update dockerfile

### PR DESCRIPTION
**Pull request by Forest-L**
Signed-off-by: “Forest-L <lilin@yunify.com>

### CODE REVIEW

**Comment by elementyang** [comment]
@Forest-L @pixiake 
I want to ask some questions：
1. Is the "kubesphere/ks-installer:v3.0.0" image compiled from this Dockerfile? 
2. Why is there no CMD instruction?
3. Where can I get the Dockerfile of "kubespheredev/shell-operator:v1.0.0-beta.5-alpine3.12" base image?
Thanks！

**Comment by Forest-L** [comment]
Refer to this issue https://github.com/kubesphere/ks-installer/pull/897/files

**Comment by elementyang** [comment]
@Forest-L 
Where can I get the Dockerfile of "kubespheredev/shell-operator:v1.0.0-beta.5-alpine3.12" base image?
Thanks!

**Comment by elementyang** [comment]
@Forest-L 
I see.
Thanks!

**Pull request merged**
