### PR TITLE
Update s2i admission webhook server certs

### PR DESCRIPTION
**Pull request by wansir**
Signed-off-by: hongming <talonwan@yunify.com>

fix: https://github.com/kubesphere/ks-installer/issues/1429

Fix bad server certificate.

### CODE REVIEW

**Comment by wansir** [comment]
Using the following command to verify 

```
kubectl apply -f https://raw.githubusercontent.com/kubesphere/ks-installer/ee57b3640402e666e4640351538278d706e34eb1/roles/ks-devops/s2i/templates/s2ioperator.yaml.j2
kubectl -n kubesphere-devops-system rollout restart sts s2ioperator
```

**Comment by JohnNiang** [comment]
Please emit a friendly error message if the specified cert is bad.

**Comment by LinuxSuRen** [comment]
hi @wansir I suggest that we put this fix into v3.1.1

If you agree with me, then I will comment with `/cherrypick release-3.1`

/cc @kubesphere/sig-devops

**Pull request merged**
