### PR TITLE
Update logsidecar injector certs

### PR DESCRIPTION
**Pull request by wansir**
Signed-off-by: hongming <talonwan@yunify.com>

fix: https://github.com/kubesphere/kubesphere/issues/3840

### CODE REVIEW

**Comment by benjaminhuo** [comment]
@junotx Pls help to review this

**Comment by wansir** [comment]
Workaround:

```
kubectl apply -f https://gist.githubusercontent.com/wansir/715eeefd3da0874272168ecd6925cfa5/raw/a452e5f2a429cd0356dfefc0ed81df8f797adcda/logsidecar-injector-certs.yaml
```

/cc @junotx

**Review by junotx — APPROVED** [review]
/lgtm

**Pull request merged**
