### PR TITLE
Fix ks-core's replicas in the managed cluster is 0

### PR DESCRIPTION
**Pull request by pixiake**
Signed-off-by: pixiake <guofeng@yunify.com>

### CODE REVIEW

**Comment by RolandMa1986** [comment]
/lgtm
btw, please change the helm chart in kubesphere/kubesphere.

**Comment by JohnNiang** [comment]
Hi @pixiake , how about cherrypicking this PR into `release-3.2` branch and releasing ks-installer `v3.2.1` base on branch `release3.2`?

**Comment by pixiake** [comment]
This fix has been included in `release-3.2`. `v3.2.0` can be used directly. Although this is confusing, the version of ks-installer should be consistent with the versions of other ks components.

**Comment by watsy0007** [comment]
cool. i'll upgrade in test env today. thx @pixiake

**Pull request merged**
