### PR TITLE
upgrade devops to 3.4.0

### PR DESCRIPTION
**Pull request by yudong2015**

### CODE REVIEW

**Comment by codering** [comment]
why revert this 
https://github.com/kubesphere/ks-installer/pull/2181 ？

**Comment by chilianyi** [comment]
> why revert the pr changes #2181 ？

Currently, it is not supported to enable CI or CD independently during deployment. Even if it is controlled in the installer, the DevOps controller will still make the calls. We will upgrade this functionality in future versions.

**Pull request merged**
