### PR TITLE
add kubesphere component alerting

### PR DESCRIPTION
**Pull request by junotx**
This synchronizes update in https://github.com/kubesphere/ks-prometheus/pull/17 to add servicemonitors and alert rules for ks-apiserver and ks-controller-manager

### CODE REVIEW

**Comment by benjaminhuo** [comment]
@pixiake would you help to take a look at why e2e failed? https://github.com/kubesphere/ks-installer/actions/runs/3111747186/jobs/5044385763

It should have nothing to do with this PR

**Comment by pixiake** [comment]
> 

ok, I just rerun this action.

**Pull request merged**
