### PR TITLE
Change the default imagePullPolicy from Always to IfNotPresent

### PR DESCRIPTION
**Pull request by LinuxSuRen**

### CODE REVIEW

**Comment by shaowenchen** [comment]
ks_image_pull_policy: Always is reasonable in master.

**Comment by LinuxSuRen** [comment]
> ks_image_pull_policy: Always is reasonable in master.

How can we make sure to change it to `IfNotPresent` when we release it.

**Comment by shaowenchen** [comment]
> > ks_image_pull_policy: Always is reasonable in master.
> 
> How can we make sure to change it to `IfNotPresent` when we release it.

It will be modified before release. We need to keep the master fresh.

**Comment by LinuxSuRen** [comment]
> It will be modified before release. We need to keep the master fresh.

Or, we can use the hash tag instead of `latest`. Always pulling images makes people feel annoyed.

**Pull request closed without merging**
