### PR TITLE
update ks-console helm chart version

### PR DESCRIPTION
**Pull request by tuoeg**
ks-console appVersion need update.

### CODE REVIEW

**Comment by benjaminhuo** [comment]
@tuoeg nice catch, I think the title should be ks-core.
@wansir @pixiake, seems that the chart version should be updated to the latest release

**Comment by tuoeg** [comment]
> 

ok,i will modify the commit

**Comment by tuoeg** [comment]
> @tuoeg nice catch, I think the title should be ks-core, not ks-console. @wansir @pixiake, seems that the chart version should be updated to the latest release

ok,i will modify the commit

**Pull request closed without merging**
