### PR TITLE
Bump ks-devops chart version from 0.1.1 to 0.1.2

### PR DESCRIPTION
**Pull request by JohnNiang**
### What this PR dose

Bump ks-devops chart version from 0.1.1 to 0.1.2.

### Why we need it

Latest ks-devops-helm-chart has been released, please see:

image

> https://github.com/kubesphere-sigs/ks-devops-helm-chart/releases/tag/ks-devops-0.1.2

/area devops

### CODE REVIEW

**Review by LinuxSuRen — APPROVED** [review]
/lgtm

**Comment by JohnNiang** [comment]
hi @pixiake , please take a moment to review this PR. If this PR don't get merged, GitHub Actions triggerd by other PR will fail.

Please see as follow:

```bash
NAMESPACE                      NAME                                                  READY   STATUS             RESTARTS   AGE
kubesphere-devops-system       devops-controller-6d5dcbdc84-v986s                    0/1     CrashLoopBackOff   6          11m
```

**Pull request merged**
