### PR TITLE
fix(ks-istio/jaeger): fix secrets "jaeger-secret" already exists

### PR DESCRIPTION
**Pull request by daixijun**

### CODE REVIEW

**Comment by JohnNiang** [comment]
Hi @daixijun , it would be better if you provide some steps to reproduce the problem with Jaeger. So that, we could verify this fix is valid.

**Comment by RolandMa1986** [comment]
@daixijun Thanks for your contribution. Overall, the changes look good to me. It would be perfect if you can provide some descriptions. I think this issue should only happen when you upgrade from ks3.1.1 to ks3.2.0 and use an external elastic search with password authentication. 
/lgtm

**Comment by daixijun** [comment]
> @daixijun Thanks for your contribution. Overall, the changes look good to me. It would be perfect if you can provide some descriptions. I think this issue should only happen when you  upgrade from ks3.1.1 to ks3.2.0 and use an external elastic search with password authentication. 
> 
> /lgtm

@RolandMa1986 yes，upgrade from ks3.1.1 to ks3.2.0 and use an external elastic search with password authentication.

**Pull request merged**
