### PR TITLE
Disabled metering module in cluser configuration.

### PR DESCRIPTION
**Pull request by yunkunrao**
Signed-off-by: yunkunrao <yunkunrao@yunify.com>

### CODE REVIEW

**Review by LinuxSuRen — CHANGES_REQUESTED** [review]
The metering module needs the configMap `ks-metering-config` if I understand it correctly.

**Comment by yunkunrao** [comment]
> The metering module needs the configMap `ks-metering-config` if I understand it correctly.

Yeah, I will add a default price configmap.

**Comment by yunkunrao** [comment]
As discussed with @pixiake , metering will be disabled by default.

**Comment by LinuxSuRen** [comment]
> And metering console will add related info to hint user add price configmap.

Is there an issue to track this task?

**Comment by yunkunrao** [comment]
https://github.com/kubesphere/ks-installer/issues/1407

**Review by LinuxSuRen — APPROVED** [review]
/lgtm

**Pull request merged**
