### PR TITLE
Update ks-core main, remove capability CRD and file

### PR DESCRIPTION
**Pull request by f10atin9**
Update ks-core so that it no longer creates CRD about storage capability, and remove useless Storage Capability files.
Signed-off-by: f10atin9 <f10atin9@kubesphere.io>

/cc @stoneshi-yunify  @pixiake 
https://github.com/kubesphere/kubesphere/issues/4075

### CODE REVIEW

**Comment by pixiake** [comment]
Does this change affect DevOps?  I find that `devops-ks-devops-apiserver` is always `CrashLoopBackOff` in ci test.
@f10atin9 @LinuxSuRen @JohnNiang

**Comment by LinuxSuRen** [comment]
> Does this change affect DevOps? I find that `devops-ks-devops-apiserver` is always `CrashLoopBackOff` in ci test.
> @f10atin9 @LinuxSuRen @JohnNiang

I try to fix this issue via https://github.com/kubesphere/kubesphere/pull/4162

**Comment by JohnNiang** [comment]
> Does this change affect DevOps? I find that `devops-ks-devops-apiserver` is always `CrashLoopBackOff` in ci test.
> @f10atin9 @LinuxSuRen @JohnNiang

Hi @pixiake , please look at this issue: https://github.com/kubesphere/ks-installer/issues/1646.

**Comment by pixiake** [comment]
> > Does this change affect DevOps? I find that `devops-ks-devops-apiserver` is always `CrashLoopBackOff` in ci test.
> > @f10atin9 @LinuxSuRen @JohnNiang
> 
> Hi @pixiake , please look at this issue: #1646.

OK, I'll fix it. This issues is caused by the rc version used in the 3.1.1 test.

**Pull request merged**
