### PR TITLE
modify default image for kubeedge cloudcore

### PR DESCRIPTION
**Pull request by zhu733756**
Signed-off-by: zhu733756 <talonzhu@yunify.com>

### CODE REVIEW

**Review by benjaminhuo — APPROVED** [review]
/lgtm

**Comment by pixiake** [comment]
Configuration parameters for images in 
https://github.com/kubesphere/ks-installer/blob/4f34972f7c91fa86c3782847872da8dc48c8d8c0/roles/download/defaults/main.yml#L117

Here should also be modified.

**Comment by zhu733756** [comment]
> Configuration parameters for images in
> https://github.com/kubesphere/ks-installer/blob/4f34972f7c91fa86c3782847872da8dc48c8d8c0/roles/download/defaults/main.yml#L117
> 
> Here should also be modified.

fixed

**Pull request merged**
