### PR TITLE
Add rule namespace:pvc_bytes_pod:sum

### PR DESCRIPTION
**Pull request by yunkunrao**
Signed-off-by: Rao Yunkun <yunkunrao@yunify.com>

### CODE REVIEW

**Review by benjaminhuo — COMMENTED** [review]
namespace:pvc_bytes_pod:sum 
=>
namespace:pvc_bytes_total:sum

**Comment by benjaminhuo** [comment]
@yunkunrao it's better to change the rule name as my comments above
@pixiake pls hold on before I review monitoring PR

**Comment by yunkunrao** [comment]
got it, I will adjust name to "namespace:pvc_bytes_total:sum" and invite @benjaminhuo  reviews before merging.

**Pull request merged**
