### PR TITLE
Upgrade kube-events to the latest version

### PR DESCRIPTION
**Pull request by wenchajun**
upgrade kube-events to v0.4.0 for ks v3.3
fix https://github.com/kubesphere/ks-installer/issues/1899

Signed-off-by: chengdehao <wenchajun@gmail.com>

### CODE REVIEW

**Comment by junotx** [comment]
@wenchajun please update the version in [task file](https://github.com/kubesphere/ks-installer/blob/master/roles/ks-events/tasks/main.yaml#L75) by the way to cover the upgrade.

**Comment by wenchajun** [comment]
> @wenchajun please update the version in [task file](https://github.com/kubesphere/ks-installer/blob/master/roles/ks-events/tasks/main.yaml#L75) by the way to cover the upgrade.

thanks ，fix

**Pull request merged**
