### PR TITLE
Delete the role-templates annotation for disabling role to users

### PR DESCRIPTION
**Pull request by zhou1203**
The purpose of this PR is to remove role-template-manage-users, role-template-manage-roles in GlobalRole, and role-template-view-members in WorkspaceRole.

Following this Issue：
[kubesphere/kubesphere#5054](https://github.com/kubesphere/kubesphere/issues/5054) [kubesphere/kubesphere#5111](https://github.com/kubesphere/kubesphere/issues/5111)

### CODE REVIEW

**Comment by wansir** [comment]
Remove the useless block directly.

**Comment by zhou1203** [comment]
After discussion, we decided to delete only their annotation `iam.kubesphere.io/module` at this stage, and the front-end filters through annotations to make some permission items invisible to users.

**Pull request merged**
