### PR TITLE
Mount metering price cm into ks-apiserver pod.

### PR DESCRIPTION
**Pull request by yunkunrao**
Signed-off-by: Rao Yunkun <yunkunrao@yunify.com>

### CODE REVIEW

**Comment by yunkunrao** [comment]
Currenly when user enable metering billing function, they need to create cm themselves and then mount the cm into the ks-apiserver pod and last not least restart the pod. This PR simplify these steps. Users only need to modify metering price cm and retart ks-apiserver.

**Comment by yunkunrao** [comment]
Currently when user enable metering billing function, they need to create cm themselves and then mount the cm into the ks-apiserver pod and last not least restart the pod. This PR simplify these steps. Users only need to modify metering price cm and restart ks-apiserver.

**Review by LinuxSuRen — APPROVED** [review]
/lgtm

**Pull request merged**
