### PR TITLE
[release-3.3] upgrade minio version to RELEASE.2022-11-08T05-27-07Z

### PR DESCRIPTION
**Pull request by besscroft**
## What type of PR is this?
/kind bug

## What this PR does / why we need it:

To See:
https://github.com/kubesphere/ks-installer/issues/2040
https://github.com/kubesphere/kubesphere/issues/5273
https://github.com/kubesphere/kubesphere/issues/5285

## Which issue(s) this PR fixes:
Fixes # RELEASE.2019-08-07T01-59-21Z  -> RELEASE.2022-11-08T05-27-07Z
Fixes # RELEASE.2019-08-07T23-14-43Z  -> RELEASE.2022-11-07T23-47-39Z

Special notes for reviewers:

```

```

Does this PR introduced a user-facing change?

```

```

Additional documentation, usage docs, etc.:

```

```

### CODE REVIEW

**Comment by besscroft** [comment]
If this version is not suitable, you can try other tested versions.

**Comment by besscroft** [comment]
The version of minio/mc also needs to be updated, but I didn't finish the test of mc.Currently I'm using the minio/mc:RELEASE.2022-11-07T23-47-39Z version.

**Comment by besscroft** [comment]
You can make ks-installer install the plugin correctly by changing the yaml inside the container.
8PF5PU(}JK)J913CL7 }8 6

**Comment by besscroft** [comment]
I created a server with the same configuration and tested it with no issues.

image

image

**Comment by pixiake** [comment]
@besscroft Thanks for this contribution !

/cherry-pick master
/lgtm
/approve

**Pull request merged**
