### PR TITLE
Refactoring the code of Controller

### PR DESCRIPTION
**Pull request by mohamed-rafraf**
```release-note
This PR refactors a previously monolithic script into splitted components
```
Aiming to enhance code maintainability, facilitate easier debugging, and support scalable development. By breaking down the code into focused modules, enabling more straightforward updates, collaborative development

In Order to test the new controller. Build docker image from `Dockerfile.complete` file!

### CODE REVIEW

**Comment by benjaminhuo** [comment]
Thanks @mohamed-rafraf  cc @pixiake

**Comment by mohamed-rafraf** [comment]
@pixiake Thank you! It's changed!

**Pull request merged**
